// Mocks generated by Mockito 5.4.5 from annotations
// in test/search_bloc_test.dart.
// Do not manually edit this file.
import 'package:mockito/mockito.dart';
import 'package:task26_2jun/domain/usecases/search_books.dart';

class MyMockSearchBooks extends Mock implements SearchBooks {}
